version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: task_manager_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: task_manager_backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://mongo:27017/task_manager
      JWT_SECRET: your-secret-key-change-in-production
      JWT_EXPIRE: 7d
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: task_manager_frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: https://team-task-manager-full-stack-3.onrender.com
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
